# ==========================================================================
# Copyright (c) Lex Ruesink (lex.ruesink@student.hu.nl) 2018
#
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE_1_0.txt or copy at
# http://www.boost.org/LICENSE_1_0.txt)
#
# ==========================================================================


# source files in this project (main.cpp is automatically assumed)
SOURCES := text_window.cpp mpu6050.cpp ../library/motion_sensor.cpp ../library/motion_rule.cpp

# header files in this project
HEADERS := text_window.hpp mpu6050.hpp ../library/motion_sensor.hpp ../library/vector3.hpp ../library/motion_rule.hpp

# other places to look for files for this project
SEARCH  := 

# set RELATIVE to the next higher directory 
# and defer to the appropriate Makefile.due.link.* there
RELATIVE := ..
include $(RELATIVE)/Makefile.due.link
